### ISSUE TITLE
isafw broken on morty

### ISSUE THREAD

**Issue by dl9pf** [01org/meta-security-isafw#82]
master is broken on morty since b45750ee93aac553142380ecd9130e5f5906eedf .

NOTE: Tasks Summary: Attempted 3639 tasks of which 3383 didn't need to be rerun and all succeeded.
ERROR: Execution of event handler 'process_reports_handler' failed
Traceback (most recent call last):
  File "/repoclone/output/../meta-security-isafw/classes/isafw.bbclass", line 95, in process_reports_handler(e=<bb.event.BuildCompleted object at 0x7fd95f7fa9d0>):
         native_sysroot = dd.expand("${STAGING_DIR}/${BUILD_ARCH}")
    >    staging_populate_sysroot_dir(target_sysroot, native_sysroot, True, dd)
      
NameError: global name 'staging_populate_sysroot_dir' is not defined

ERROR: Running idle function
Traceback (most recent call last):
  File "/repoclone/poky/bitbake/lib/bb/cooker.py", line 1392, in buildTargetsIdle(server=<ProcessServer(ProcessServer-1, started)>, rq=<bb.runqueue.RunQueue instance at 0x7fd9542d05a8>, abort=False):
                 if not retval:
    >                bb.event.fire(bb.event.BuildCompleted(len(rq.rqdata.runq_fnid), buildname, targets, failures, interrupted), self.data)
                     self.command.finishAsyncCommand(msg)
  File "/repoclone/poky/bitbake/lib/bb/event.py", line 178, in fire(event=<bb.event.BuildCompleted object at 0x7fd95f7fa9d0>, d=<bb.data_smart.DataSmart object at 0x7fd96895f390>):
     
    >    fire_class_handlers(event, d)
         if worker_fire:
  File "/repoclone/poky/bitbake/lib/bb/event.py", line 110, in fire_class_handlers(event=<bb.event.BuildCompleted object at 0x7fd95f7fa9d0>, d=<bb.data_smart.DataSmart object at 0x7fd96895f390>):
                         continue
    >            execute_handler(name, handler, event, d)
     
  File "/repoclone/poky/bitbake/lib/bb/event.py", line 82, in execute_handler(name='process_reports_handler', handler=<function process_reports_handler at 0x7fd965bf9b90>, event=<bb.event.BuildCompleted object at 0x7fd95f7fa9d0>, d=<bb.data_smart.DataSmart object at 0x7fd96895f390>):
         try:
    >        ret = handler(event)
         except (bb.parse.SkipRecipe, bb.BBHandledException):
  File "/repoclone/output/../meta-security-isafw/classes/isafw.bbclass", line 95, in process_reports_handler(e=<bb.event.BuildCompleted object at 0x7fd95f7fa9d0>):
         native_sysroot = dd.expand("${STAGING_DIR}/${BUILD_ARCH}")
    >    staging_populate_sysroot_dir(target_sysroot, native_sysroot, True, dd)
      
NameError: global name 'staging_populate_sysroot_dir' is not defined

## Failed again, bail out ...

**Comment by ereshetova** [comment]
Oh, yes, I keep forgetting that not everyone follows latest and greatest Yocto changes. 
Let me do a separate morty branch without these changes. I will keep maintaining it till next release is fully out.

**Comment by ereshetova** [comment]
Here is the branch: https://github.com/01org/meta-security-isafw/tree/morty

I don't have morty anywhere locally now, so could you please check if it runs for your environment? 
I kept the important fixes in and only removed the non-combatible sysroot changes.

**Comment by dl9pf** [comment]
Cool I'll try it !

**Comment by ereshetova** [comment]
Can we close this issue?
